# Generated by Django 5.1.3 on 2024-12-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
