# Generated by Django 5.1.3 on 2024-12-12 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Telefon raqami faqat raqamlardan iborat bo‘lishi kerak.",
                        regex="^\\d+$",
                    )
                ],
            ),
        ),
    ]
