# Generated by Django 5.1.3 on 2024-12-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_alter_restaurant_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.IntegerField(max_length=20),
        ),
    ]
