# Generated by Django 5.1.3 on 2024-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_alter_restaurant_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="map_location",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="restaurant_images/"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
