# Generated by Django 5.1.3 on 2024-12-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurants",
            "0004_remove_restaurant_map_location_restaurant_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
